name: CI - Terraform Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate-dev:
    name: Validar DEV
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Infra/dev

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Verificação de segurança (checkov)
        run: |
          pip install checkov --quiet
          checkov -d . --framework terraform --soft-fail

  validate-hml:
    name: Validar HML
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Infra/hml

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate